name: Excel2RDF
on:
    push:
      branches:
        - main
      paths:
        - '**.xlsx'
jobs:
  excel2rdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

    - name: Check and Alert if watched files changed
      id: check-and-alert
      env:
        SKOSPlay_URL: https://skos-play.sparna.fr/play/excel_test/excel2skos-exemple-1.xlsx
      run: 
        # Define the list of filenames to watch for changes

        #watched_files=("**.xlsx" "**.xls")
        #if [[ ${{ github.event_name }} == 'pull_request' ]]; then
        changed_files=$(git diff --name-only -r HEAD^1 HEAD)
        #else
        #  changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
        #fi
        for file in $changed_files; do
          for watched_file in "${watched_files[@]}"; do
            if [[ $file == *"$watched_file"* ]]; then
              curl -X POST -H 'Content-type: application/json' --data '{"text":"File changed: '"$file"' "}' $SKOSPlay_URL
            fi
          done
        done