name: Excel2RDF
on:
    push:
      branches:
        - develop
      paths:
        - '**.xlsx'
    

permissions:
  contents: read
  pull-requests: read

jobs:
  Excel2RDF:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6
        with:
            configFile: "./.commitlintrc.json"
