name: Excel2RDF
on:
    push:
      branches:
        - main
      paths:
        - '**.xlsx'
jobs:
  Excel2RDF:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run convert script
        run: python excel2rdf.py