name: Excel2RDF
on:
    push:
      branches:
        - main
      paths:
        - '**.xlsx'
jobs:
  excel2rdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

    - name: Check and Alert if watched files changed
      id: check-and-alert
      env:
        SKOSPlay_URL: https://xls2rdf.sparna.fr/rest/convert        
      run:
        #echo $SKOSPlay_URL
        #echo ${{github.workspace}}
        #echo ${{github.path}}
        changed_files=$(git diff --name-only -r HEAD^1 HEAD)
        for file in $changed_files
          echo $file
          echo "$file"
          cmd = "https://xls2rdf.sparna.fr/rest/convert?url=https://raw.githubusercontent.com/${{github.repository}}/main/$file&noPostprocessings=true"
          echo “$cmd"
          curl "$cmd"
        done