name: Excel2RDF
on:
    push:
      branches:
        - main
      paths:
        - '**.xlsx'
jobs:
  excel2rdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

    - name: Check and Alert if watched files changed
      id: check-and-alert
      env:
        SKOSPlay_URL: https://skos-play.sparna.fr/play/excel_test/excel2skos-exemple-1.xlsx
      run:
        echo $SKOSPlay_URL